### ISSUE TITLE
【バグ/bug】ログインボーナスが受け取れない

### ISSUE THREAD

**Issue by ksdev-jp** [Ks-777/ShibakenBot#9]
## 発生日時・発生した機能・コマンド
11月15日ごろの新機能追加(/tyouhanコマンドの追加&バグ修正)からログインボーナスが機能しないことが判明していします。

## バグの概要(どのようなバグか)

現在のところ、ログインボーナスのデータを保存している.jsonファイルがリセットしてないことがほぼ確定しています。

## 正しい動作
24時をまたいだ新しい日になった時(JST)に正常にログインボーナス記録ファイルがリセットされ、ログインボーナスを受け取れる

## 再現方法(バグを起こす方法)

ログインする。

## その他/Other
バグの原因を突き止めた気がするのでIssueで整理します。

**Comment by Ks-777** [comment]
とりあえずファイルリセット機構を新しく変えてみて、様子を見ます。

**Comment by Ks-777** [comment]
原因機能の改善は今日中にプルリクエストを提出します。
提出前に実行している本サーバーを稼働させるため、場合に応じて修正できない場合があります。
その場合は機能を一旦コメントアウトし、放棄します。

**Comment by Ks-777** [comment]
BOTファイル復活して作業できそうなので、明日中に復活
コードは書けた

**Comment by Ks-777** [comment]
https://github.com/Ks-777/ShibakenBot/commit/173cd7e385071ba9ad9720c01ac036538be05f5a
で修正
(テスト･確認済)
